version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - react_app:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - web

  frontend:
    build: ./frontend
    volumes:
      - react_app:/app/build
    depends_on:
      - nginx
  
volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_app: